---
 - name: Playbook to intialize Kubernetes on Main Master
   hosts: main-master
   become: yes
   vars_files: 
     - /home/ubuntu/ha-ip.yml
   tasks:
    
    - name: Initialize the Kubernetes control plane on the master-node-main
      shell: sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket /run/cri-dockerd.sock --upload-certs --control-plane-endpoint {{ha_prv_ip}}:6443
      register: output

    - name: Storing Logs and Generated token for future purpose.
      local_action: copy content={{ output.stdout }} dest="/tmp/token" mode=0777
    
    - name: Create directory and copy required file to it-Set up the kubeconfig file for your regular user account
      shell: |
        sudo su -c 'mkdir -p $HOME/.kube' ubuntu
        sudo su -c 'sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config' ubuntu
        sudo su -c 'sudo chown $(id -u):$(id -g) $HOME/.kube/config' ubuntu
    
    - name: Retrieve the config file from the master-node-main to ansible host
      run_once: yes
      fetch: src=/home/ubuntu/.kube/config dest=/home/ubuntu/ flat=yes