---
 - name: Ansible Playbook for Stage Environment
   hosts: haproxy
   become: true

   tasks:

   - name: Removing the Previous Application Repo for Update  
     shell: rm -rf Sock-Shop-App-Repo
     ignore_errors: yes
     args:
       chdir: /home/ubuntu

   - name: Cloning Application Repo to get the Latest Update
     shell: git clone https://github.com/mr-lington/Sock-Shop.git 

   - name: Deleting Previous Deployment to Stage  
     shell: sudo su -c 'kubectl delete -f staging-complete.yaml' ubuntu
     ignore_errors: yes     
     args:
       chdir: Sock-Shop-App-Repo/deploy/kubernetes

   - name: Deploying Latest Update to Stage  
     shell: sudo su -c 'kubectl apply -f staging-complete.yaml' ubuntu     
     args:
       chdir: Sock-Shop-App-Repo/deploy/kubernetes