# variable "domain" {}
# variable "domain2" {}
# variable "domain-prometheus" {}
# variable "domain-grafana" {}
# variable "domain-stage" {}
# variable "domain-prod" {}
# variable "ami-ubuntu" {}
# variable "ami-redhat" {}
# variable "instance_type" {}
# variable "instance_type2" {}
# variable "keypair" {}
# variable "newrelic-id" {}
# variable "newrelic-license-key" {}
# variable "instance-count" {}